export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";